//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//       LottieGen version:
//           8.2.250604.1+b02a3ee244
//       
//       Command:
//           LottieGen -Language CSharp -Public -WinUIVersion 3.0 -InputFile Sad - Failed.json
//       
//       Input file:
//           Sad - Failed.json (29617 bytes created 21:24+08:00 Aug 19 2025)
//       
//       LottieGen source:
//           http://aka.ms/Lottie
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ____________________________________
// |       Object stats       | Count |
// |__________________________|_______|
// | All CompositionObjects   |   102 |
// |--------------------------+-------|
// | Expression animators     |     1 |
// | KeyFrame animators       |    14 |
// | Reference parameters     |     1 |
// | Expression operations    |     0 |
// |--------------------------+-------|
// | Animated brushes         |     - |
// | Animated gradient stops  |     - |
// | ExpressionAnimations     |     1 |
// | PathKeyFrameAnimations   |     1 |
// |--------------------------+-------|
// | ContainerVisuals         |     1 |
// | ShapeVisuals             |     1 |
// |--------------------------+-------|
// | ContainerShapes          |     8 |
// | CompositionSpriteShapes  |    12 |
// |--------------------------+-------|
// | Brushes                  |     3 |
// | Gradient stops           |     - |
// | CompositionVisualSurface |     - |
// ------------------------------------
using Microsoft.Graphics;
using Microsoft.Graphics.Canvas.Geometry;
using Microsoft.UI.Composition;
using System;
using System.Collections.Generic;
using System.Numerics;
using Windows.UI;

namespace AnimatedVisuals
{
    // Name:        Sad
    // Frame rate:  25 fps
    // Frame count: 110
    // Duration:    4400.0 mS
    public partial class SadFailed
        : Microsoft.UI.Xaml.Controls.IAnimatedVisualSource
        , Microsoft.UI.Xaml.Controls.IAnimatedVisualSource2
    {
        // Animation duration: 4.400 seconds.
        internal const long c_durationTicks = 44000000;

        public Microsoft.UI.Xaml.Controls.IAnimatedVisual TryCreateAnimatedVisual(Compositor compositor)
        {
            object ignored = null;
            return TryCreateAnimatedVisual(compositor, out ignored);
        }

        public Microsoft.UI.Xaml.Controls.IAnimatedVisual TryCreateAnimatedVisual(Compositor compositor, out object diagnostics)
        {
            diagnostics = null;

            var res = 
                new Sad__Failed_AnimatedVisual(
                    compositor
                    );
                res.CreateAnimations();
                return res;
        }

        /// <summary>
        /// Gets the number of frames in the animation.
        /// </summary>
        public double FrameCount => 110d;

        /// <summary>
        /// Gets the frame rate of the animation.
        /// </summary>
        public double Framerate => 25d;

        /// <summary>
        /// Gets the duration of the animation.
        /// </summary>
        public TimeSpan Duration => TimeSpan.FromTicks(44000000);

        /// <summary>
        /// Converts a zero-based frame number to the corresponding progress value denoting the
        /// start of the frame.
        /// </summary>
        public double FrameToProgress(double frameNumber)
        {
            return frameNumber / 110d;
        }

        /// <summary>
        /// Returns a map from marker names to corresponding progress values.
        /// </summary>
        public IReadOnlyDictionary<string, double> Markers =>
            new Dictionary<string, double>
            {
            };

        /// <summary>
        /// Sets the color property with the given name, or does nothing if no such property
        /// exists.
        /// </summary>
        public void SetColorProperty(string propertyName, Color value)
        {
        }

        /// <summary>
        /// Sets the scalar property with the given name, or does nothing if no such property
        /// exists.
        /// </summary>
        public void SetScalarProperty(string propertyName, double value)
        {
        }

        public partial class Sad__Failed_AnimatedVisual
            : Microsoft.UI.Xaml.Controls.IAnimatedVisual
            , Microsoft.UI.Xaml.Controls.IAnimatedVisual2
        {
            const long c_durationTicks = 44000000;
            readonly Compositor _c;
            readonly ExpressionAnimation _reusableExpressionAnimation;
            AnimationController _animationController_0;
            CompositionColorBrush _colorBrush_AlmostDarkSlateGray_FF333333;
            CompositionColorBrush _colorBrush_White;
            CompositionContainerShape _containerShape_0;
            CompositionContainerShape _containerShape_1;
            CompositionContainerShape _containerShape_2;
            CompositionContainerShape _containerShape_3;
            CompositionContainerShape _containerShape_4;
            CompositionContainerShape _containerShape_5;
            CompositionContainerShape _containerShape_6;
            CompositionContainerShape _containerShape_7;
            CompositionEllipseGeometry _ellipse_5p489;
            CompositionEllipseGeometry _ellipse_24p164;
            CompositionEllipseGeometry _ellipse_58p497;
            CompositionPath _path_0;
            CompositionPath _path_1;
            CompositionPathGeometry _pathGeometry_0;
            CompositionPathGeometry _pathGeometry_1;
            CompositionSpriteShape _spriteShape_05;
            CompositionSpriteShape _spriteShape_10;
            CompositionSpriteShape _spriteShape_11;
            ContainerVisual _root;
            CubicBezierEasingFunction _cubicBezierEasingFunction_0;
            CubicBezierEasingFunction _cubicBezierEasingFunction_1;
            CubicBezierEasingFunction _cubicBezierEasingFunction_2;
            CubicBezierEasingFunction _cubicBezierEasingFunction_3;
            StepEasingFunction _holdThenStepEasingFunction;
            StepEasingFunction _stepThenHoldEasingFunction;
            Vector2KeyFrameAnimation _scaleVector2Animation_1;
            Vector2KeyFrameAnimation _scaleVector2Animation_2;

            void BindProperty(
                CompositionObject target,
                string animatedPropertyName,
                string expression,
                string referenceParameterName,
                CompositionObject referencedObject)
            {
                _reusableExpressionAnimation.ClearAllParameters();
                _reusableExpressionAnimation.Expression = expression;
                _reusableExpressionAnimation.SetReferenceParameter(referenceParameterName, referencedObject);
                target.StartAnimation(animatedPropertyName, _reusableExpressionAnimation);
            }

            PathKeyFrameAnimation CreatePathKeyFrameAnimation(float initialProgress, CompositionPath initialValue, CompositionEasingFunction initialEasingFunction)
            {
                var result = _c.CreatePathKeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(initialProgress, initialValue, initialEasingFunction);
                return result;
            }

            Vector2KeyFrameAnimation CreateVector2KeyFrameAnimation(float initialProgress, Vector2 initialValue, CompositionEasingFunction initialEasingFunction)
            {
                var result = _c.CreateVector2KeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(initialProgress, initialValue, initialEasingFunction);
                return result;
            }

            CompositionSpriteShape CreateSpriteShape(CompositionGeometry geometry, Matrix3x2 transformMatrix, CompositionBrush fillBrush)
            {
                var result = _c.CreateSpriteShape(geometry);
                result.TransformMatrix = transformMatrix;
                result.FillBrush = fillBrush;
                return result;
            }

            AnimationController AnimationController_0()
            {
                if (_animationController_0 != null) { return _animationController_0; }
                var result = _animationController_0 = _c.CreateAnimationController();
                result.Pause();
                BindProperty(_animationController_0, "Progress", "_.Progress", "_", _root);
                return result;
            }

            CanvasGeometry Geometry_0()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.BeginFigure(new Vector2(-105.234001F, -137.528F));
                    builder.AddCubicBezier(new Vector2(-105.234001F, -137.528F), new Vector2(-121.936996F, -90.7570038F), new Vector2(-155.345001F, -82.961998F));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_1()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.BeginFigure(new Vector2(-101.892998F, 110.802002F));
                    builder.AddCubicBezier(new Vector2(-101.892998F, 110.802002F), new Vector2(-59.3100014F, 65.6539993F), new Vector2(-1.30700004F, 67.2919998F));
                    builder.AddCubicBezier(new Vector2(26.1450005F, 68.0670013F), new Vector2(57.0499992F, 79.3219986F), new Vector2(88.5299988F, 110.802002F));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_2()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.BeginFigure(new Vector2(-64.1110001F, 95.276001F));
                    builder.AddCubicBezier(new Vector2(-64.1110001F, 95.276001F), new Vector2(-58.2840004F, 52.1669998F), new Vector2(-0.307000011F, 54.5740013F));
                    builder.AddCubicBezier(new Vector2(22F, 55.5F), new Vector2(36.5F, 62F), new Vector2(54.0690002F, 94.776001F));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CompositionColorBrush ColorBrush_AlmostDarkSlateGray_FF333333()
            {
                return (_colorBrush_AlmostDarkSlateGray_FF333333 == null)
                    ? _colorBrush_AlmostDarkSlateGray_FF333333 = _c.CreateColorBrush(Color.FromArgb(0xFF, 0x33, 0x33, 0x33))
                    : _colorBrush_AlmostDarkSlateGray_FF333333;
            }

            // - - Layer aggregator
            // ShapeGroup: Ellipse 1 Offset:<-1.079, -2.193>
            CompositionColorBrush ColorBrush_AlmostGoldenrod_FFFFAF30()
            {
                return _c.CreateColorBrush(Color.FromArgb(0xFF, 0xFF, 0xAF, 0x30));
            }

            CompositionColorBrush ColorBrush_White()
            {
                return (_colorBrush_White == null)
                    ? _colorBrush_White = _c.CreateColorBrush(Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF))
                    : _colorBrush_White;
            }

            // Layer aggregator
            CompositionContainerShape ContainerShape_0()
            {
                if (_containerShape_0 != null) { return _containerShape_0; }
                var result = _containerShape_0 = _c.CreateContainerShape();
                result.CenterPoint = new Vector2(-1.079F, 221.115005F);
                result.Offset = new Vector2(250F, 249.999985F);
                // ShapeGroup: Ellipse 1 Offset:<-1.079, -2.193>
                result.Shapes.Add(SpriteShape_00());
                return result;
            }

            // Layer aggregator
            CompositionContainerShape ContainerShape_1()
            {
                if (_containerShape_1 != null) { return _containerShape_1; }
                var result = _containerShape_1 = _c.CreateContainerShape();
                var shapes = result.Shapes;
                // Transforms: Shape Layer 2
                shapes.Add(ContainerShape_2());
                // Transforms: Shape Layer 12
                shapes.Add(SpriteShape_05());
                // Transforms: Shape Layer 13
                shapes.Add(ContainerShape_5());
                // Transforms: Shape Layer 17
                shapes.Add(SpriteShape_10());
                // Transforms: M
                shapes.Add(SpriteShape_11());
                return result;
            }

            // - Layer aggregator
            // Transforms for Shape Layer 2
            CompositionContainerShape ContainerShape_2()
            {
                if (_containerShape_2 != null) { return _containerShape_2; }
                var result = _containerShape_2 = _c.CreateContainerShape();
                result.CenterPoint = new Vector2(-87.9400024F, -45.6240005F);
                result.Offset = new Vector2(57.9400024F, 95.6240005F);
                var shapes = result.Shapes;
                // ShapeGroup: Ellipse 1 Offset:<-87.94, -45.624>
                shapes.Add(SpriteShape_01());
                // Transforms: Shape Layer 3 Scale:0.91,0.91
                shapes.Add(SpriteShape_02());
                // Transforms: Shape Layer 3 Scale:0.91,0.91
                shapes.Add(ContainerShape_3());
                // Transforms: Shape Layer 3 Scale:0.91,0.91
                shapes.Add(ContainerShape_4());
                return result;
            }

            // - - Layer aggregator
            // Transforms: Shape Layer 2
            // Transforms for Shape Layer 4
            CompositionContainerShape ContainerShape_3()
            {
                if (_containerShape_3 != null) { return _containerShape_3; }
                var result = _containerShape_3 = _c.CreateContainerShape();
                result.CenterPoint = new Vector2(-103.813004F, -66.6380005F);
                result.Offset = new Vector2(3.45800018F, 3.33399963F);
                result.RotationAngleInDegrees = -13.927F;
                // Offset:<-11.064597, -8.335798>, Scale:<0.91, 0.91>
                result.TransformMatrix = new Matrix3x2(0.910000026F, 0F, 0F, 0.910000026F, -11.0645971F, -8.33579826F);
                // ShapeGroup: Ellipse 1 Scale:0.85074,0.68751, RotationDegrees:-16.517000198364258,
                // Offset:<-103.813, -66.638>
                result.Shapes.Add(SpriteShape_03());
                return result;
            }

            // - - Layer aggregator
            // Transforms: Shape Layer 2
            // Transforms for Shape Layer 5
            CompositionContainerShape ContainerShape_4()
            {
                if (_containerShape_4 != null) { return _containerShape_4; }
                var result = _containerShape_4 = _c.CreateContainerShape();
                result.CenterPoint = new Vector2(-75.5110016F, -29.0109997F);
                result.Offset = new Vector2(4.69100189F, 6.29100037F);
                // Offset:<-11.064597, -8.335798>, Scale:<0.91, 0.91>
                result.TransformMatrix = new Matrix3x2(0.910000026F, 0F, 0F, 0.910000026F, -11.0645971F, -8.33579826F);
                // ShapeGroup: Ellipse 1 Offset:<-75.511, -29.011>
                result.Shapes.Add(SpriteShape_04());
                return result;
            }

            // - Layer aggregator
            // Transforms for Shape Layer 13
            CompositionContainerShape ContainerShape_5()
            {
                if (_containerShape_5 != null) { return _containerShape_5; }
                var result = _containerShape_5 = _c.CreateContainerShape();
                result.CenterPoint = new Vector2(-87.9400024F, -45.6240005F);
                result.Offset = new Vector2(217.940002F, 95.6240005F);
                var shapes = result.Shapes;
                // ShapeGroup: Ellipse 1 Offset:<-87.94, -45.624>
                shapes.Add(SpriteShape_06());
                // Transforms: Shape Layer 14 Scale:-0.91,0.91, Offset:<-3.149994, -4.2299995>
                shapes.Add(SpriteShape_07());
                // Transforms: Shape Layer 14 Scale:-0.91,0.91, Offset:<-3.149994, -4.2299995>
                shapes.Add(ContainerShape_6());
                // Transforms: Shape Layer 14 Scale:-0.91,0.91, Offset:<-3.149994, -4.2299995>
                shapes.Add(ContainerShape_7());
                return result;
            }

            // - - Layer aggregator
            // Transforms: Shape Layer 13
            // Transforms for Shape Layer 15
            CompositionContainerShape ContainerShape_6()
            {
                if (_containerShape_6 != null) { return _containerShape_6; }
                var result = _containerShape_6 = _c.CreateContainerShape();
                result.CenterPoint = new Vector2(-103.813004F, -66.6380005F);
                result.Offset = new Vector2(3.45800018F, 3.33399963F);
                result.RotationAngleInDegrees = -13.927F;
                // Offset:<-171.1154, -8.336159>, Scale:<0.91, -0.91>
                result.TransformMatrix = new Matrix3x2(-0.910000026F, 0F, 0F, 0.910000026F, -171.115402F, -8.33615875F);
                // ShapeGroup: Ellipse 1 Scale:0.85074,0.68751, RotationDegrees:-16.517000198364258,
                // Offset:<-103.813, -66.638>
                result.Shapes.Add(SpriteShape_08());
                return result;
            }

            // - - Layer aggregator
            // Transforms: Shape Layer 13
            // Transforms for Shape Layer 16
            CompositionContainerShape ContainerShape_7()
            {
                if (_containerShape_7 != null) { return _containerShape_7; }
                var result = _containerShape_7 = _c.CreateContainerShape();
                result.CenterPoint = new Vector2(-75.5110016F, -29.0109997F);
                result.Offset = new Vector2(4.69100189F, 6.29100037F);
                // Offset:<-171.1154, -8.336159>, Scale:<0.91, -0.91>
                result.TransformMatrix = new Matrix3x2(-0.910000026F, 0F, 0F, 0.910000026F, -171.115402F, -8.33615875F);
                // ShapeGroup: Ellipse 1 Offset:<-75.511, -29.011>
                result.Shapes.Add(SpriteShape_09());
                return result;
            }

            // Ellipse Path 1.EllipseGeometry
            CompositionEllipseGeometry Ellipse_5p489()
            {
                if (_ellipse_5p489 != null) { return _ellipse_5p489; }
                var result = _ellipse_5p489 = _c.CreateEllipseGeometry();
                result.Radius = new Vector2(5.48899984F, 5.48899984F);
                return result;
            }

            // Ellipse Path 1.EllipseGeometry
            CompositionEllipseGeometry Ellipse_24p164()
            {
                if (_ellipse_24p164 != null) { return _ellipse_24p164; }
                var result = _ellipse_24p164 = _c.CreateEllipseGeometry();
                result.Radius = new Vector2(24.1639996F, 24.1639996F);
                return result;
            }

            // Ellipse Path 1.EllipseGeometry
            CompositionEllipseGeometry Ellipse_58p497()
            {
                if (_ellipse_58p497 != null) { return _ellipse_58p497; }
                var result = _ellipse_58p497 = _c.CreateEllipseGeometry();
                result.Radius = new Vector2(58.4964981F, 58.4964981F);
                return result;
            }

            // - - Layer aggregator
            // ShapeGroup: Ellipse 1 Offset:<-1.079, -2.193>
            // Ellipse Path 1.EllipseGeometry
            CompositionEllipseGeometry Ellipse_223p309()
            {
                var result = _c.CreateEllipseGeometry();
                result.Radius = new Vector2(223.308502F, 223.308502F);
                return result;
            }

            CompositionPath Path_0()
            {
                if (_path_0 != null) { return _path_0; }
                var result = _path_0 = new CompositionPath(Geometry_1());
                return result;
            }

            CompositionPath Path_1()
            {
                if (_path_1 != null) { return _path_1; }
                var result = _path_1 = new CompositionPath(Geometry_2());
                return result;
            }

            CompositionPathGeometry PathGeometry_0()
            {
                return (_pathGeometry_0 == null)
                    ? _pathGeometry_0 = _c.CreatePathGeometry(new CompositionPath(Geometry_0()))
                    : _pathGeometry_0;
            }

            // - - Layer aggregator
            // Transforms: M
            CompositionPathGeometry PathGeometry_1()
            {
                if (_pathGeometry_1 != null) { return _pathGeometry_1; }
                var result = _pathGeometry_1 = _c.CreatePathGeometry();
                return result;
            }

            // - Layer aggregator
            // Ellipse Path 1
            CompositionSpriteShape SpriteShape_00()
            {
                // Offset:<-1.079, -2.193>
                var geometry = Ellipse_223p309();
                var result = CreateSpriteShape(geometry, new Matrix3x2(1F, 0F, 0F, 1F, -1.079F, -2.19300008F), ColorBrush_AlmostGoldenrod_FFFFAF30());;
                return result;
            }

            // - - Layer aggregator
            // Transforms: Shape Layer 2
            // Ellipse Path 1
            CompositionSpriteShape SpriteShape_01()
            {
                // Offset:<-87.94, -45.624>
                var geometry = Ellipse_58p497();
                var result = CreateSpriteShape(geometry, new Matrix3x2(1F, 0F, 0F, 1F, -87.9400024F, -45.6240005F), ColorBrush_White());;
                return result;
            }

            // - - Layer aggregator
            // Transforms: Shape Layer 2
            // Ellipse Path 1
            CompositionSpriteShape SpriteShape_02()
            {
                // Offset:<-91.090004, -49.853638>, Scale:<0.91, 0.91>
                var geometry = Ellipse_58p497();
                var result = CreateSpriteShape(geometry, new Matrix3x2(0.910000026F, 0F, 0F, 0.910000026F, -91.090004F, -49.8536377F), ColorBrush_AlmostDarkSlateGray_FF333333());;
                return result;
            }

            // - - - Layer aggregator
            // - Transforms: Shape Layer 2
            // Transforms: Shape Layer 3 Scale:0.91,0.91
            // Ellipse Path 1
            CompositionSpriteShape SpriteShape_03()
            {
                // Offset:<-103.813, -66.638>, Rotation:-16.517002211630455 degrees,
                // Scale:<0.85073996, 0.68750995>, Skew:<2.0588582E-08, 0>
                var geometry = Ellipse_24p164();
                var result = CreateSpriteShape(geometry, new Matrix3x2(0.815634549F, -0.241865233F, 0.195458978F, 0.65914017F, -103.813004F, -66.6380005F), ColorBrush_White());;
                return result;
            }

            // - - - Layer aggregator
            // - Transforms: Shape Layer 2
            // Transforms: Shape Layer 3 Scale:0.91,0.91
            // Ellipse Path 1
            CompositionSpriteShape SpriteShape_04()
            {
                // Offset:<-75.511, -29.011>
                var geometry = Ellipse_5p489();
                var result = CreateSpriteShape(geometry, new Matrix3x2(1F, 0F, 0F, 1F, -75.5110016F, -29.0109997F), ColorBrush_White());;
                return result;
            }

            // - Layer aggregator
            // Path 1
            CompositionSpriteShape SpriteShape_05()
            {
                if (_spriteShape_05 != null) { return _spriteShape_05; }
                var result = _spriteShape_05 = _c.CreateSpriteShape(PathGeometry_0());
                result.CenterPoint = new Vector2(-130.289993F, -110.245003F);
                result.RotationAngleInDegrees = 19F;
                result.StrokeBrush = ColorBrush_AlmostDarkSlateGray_FF333333();
                result.StrokeDashCap = CompositionStrokeCap.Round;
                result.StrokeStartCap = CompositionStrokeCap.Round;
                result.StrokeEndCap = CompositionStrokeCap.Round;
                result.StrokeLineJoin = CompositionStrokeLineJoin.Round;
                result.StrokeMiterLimit = 2F;
                result.StrokeThickness = 19F;
                return result;
            }

            // - - Layer aggregator
            // Transforms: Shape Layer 13
            // Ellipse Path 1
            CompositionSpriteShape SpriteShape_06()
            {
                // Offset:<-87.94, -45.624>
                var geometry = Ellipse_58p497();
                var result = CreateSpriteShape(geometry, new Matrix3x2(1F, 0F, 0F, 1F, -87.9400024F, -45.6240005F), ColorBrush_White());;
                return result;
            }

            // - - Layer aggregator
            // Transforms: Shape Layer 13
            // Ellipse Path 1
            CompositionSpriteShape SpriteShape_07()
            {
                // Offset:<-91.09, -49.854>, Scale:<0.91, -0.91>
                var geometry = Ellipse_58p497();
                var result = CreateSpriteShape(geometry, new Matrix3x2(-0.910000026F, 0F, 0F, 0.910000026F, -91.0899963F, -49.8540001F), ColorBrush_AlmostDarkSlateGray_FF333333());;
                return result;
            }

            // - - - Layer aggregator
            // - Transforms: Shape Layer 13
            // Transforms: Shape Layer 14 Scale:-0.91,0.91, Offset:<-3.149994, -4.2299995>
            // Ellipse Path 1
            CompositionSpriteShape SpriteShape_08()
            {
                // Offset:<-103.813, -66.638>, Rotation:-16.517002211630455 degrees,
                // Scale:<0.85073996, 0.68750995>, Skew:<2.0588582E-08, 0>
                var geometry = Ellipse_24p164();
                var result = CreateSpriteShape(geometry, new Matrix3x2(0.815634549F, -0.241865233F, 0.195458978F, 0.65914017F, -103.813004F, -66.6380005F), ColorBrush_White());;
                return result;
            }

            // - - - Layer aggregator
            // - Transforms: Shape Layer 13
            // Transforms: Shape Layer 14 Scale:-0.91,0.91, Offset:<-3.149994, -4.2299995>
            // Ellipse Path 1
            CompositionSpriteShape SpriteShape_09()
            {
                // Offset:<-75.511, -29.011>
                var geometry = Ellipse_5p489();
                var result = CreateSpriteShape(geometry, new Matrix3x2(1F, 0F, 0F, 1F, -75.5110016F, -29.0109997F), ColorBrush_White());;
                return result;
            }

            // - Layer aggregator
            // Path 1
            CompositionSpriteShape SpriteShape_10()
            {
                if (_spriteShape_10 != null) { return _spriteShape_10; }
                var result = _spriteShape_10 = _c.CreateSpriteShape(PathGeometry_0());
                result.CenterPoint = new Vector2(-130.289993F, -110.245003F);
                result.RotationAngleInDegrees = -19F;
                result.StrokeBrush = ColorBrush_AlmostDarkSlateGray_FF333333();
                result.StrokeDashCap = CompositionStrokeCap.Round;
                result.StrokeStartCap = CompositionStrokeCap.Round;
                result.StrokeEndCap = CompositionStrokeCap.Round;
                result.StrokeLineJoin = CompositionStrokeLineJoin.Round;
                result.StrokeMiterLimit = 2F;
                result.StrokeThickness = 19F;
                return result;
            }

            // - Layer aggregator
            // Path 1
            CompositionSpriteShape SpriteShape_11()
            {
                if (_spriteShape_11 != null) { return _spriteShape_11; }
                var result = _spriteShape_11 = _c.CreateSpriteShape(PathGeometry_1());
                result.Offset = new Vector2(50F, 95.6240005F);
                result.StrokeBrush = ColorBrush_AlmostDarkSlateGray_FF333333();
                result.StrokeDashCap = CompositionStrokeCap.Round;
                result.StrokeStartCap = CompositionStrokeCap.Round;
                result.StrokeEndCap = CompositionStrokeCap.Round;
                result.StrokeLineJoin = CompositionStrokeLineJoin.Round;
                result.StrokeMiterLimit = 2F;
                result.StrokeThickness = 19F;
                return result;
            }

            // The root of the composition.
            ContainerVisual Root()
            {
                if (_root != null) { return _root; }
                var result = _root = _c.CreateContainerVisual();
                var propertySet = result.Properties;
                propertySet.InsertScalar("Progress", 0F);
                // Layer aggregator
                result.Children.InsertAtTop(ShapeVisual_0());
                return result;
            }

            CubicBezierEasingFunction CubicBezierEasingFunction_0()
            {
                return (_cubicBezierEasingFunction_0 == null)
                    ? _cubicBezierEasingFunction_0 = _c.CreateCubicBezierEasingFunction(new Vector2(0.333000004F, 0F), new Vector2(0.666999996F, 1F))
                    : _cubicBezierEasingFunction_0;
            }

            CubicBezierEasingFunction CubicBezierEasingFunction_1()
            {
                return (_cubicBezierEasingFunction_1 == null)
                    ? _cubicBezierEasingFunction_1 = _c.CreateCubicBezierEasingFunction(new Vector2(0.166999996F, 0F), new Vector2(0.666999996F, 1F))
                    : _cubicBezierEasingFunction_1;
            }

            CubicBezierEasingFunction CubicBezierEasingFunction_2()
            {
                return (_cubicBezierEasingFunction_2 == null)
                    ? _cubicBezierEasingFunction_2 = _c.CreateCubicBezierEasingFunction(new Vector2(0.166999996F, 0F), new Vector2(0.833000004F, 1F))
                    : _cubicBezierEasingFunction_2;
            }

            CubicBezierEasingFunction CubicBezierEasingFunction_3()
            {
                return (_cubicBezierEasingFunction_3 == null)
                    ? _cubicBezierEasingFunction_3 = _c.CreateCubicBezierEasingFunction(new Vector2(0.166999996F, 0.166999996F), new Vector2(0.666999996F, 0.666999996F))
                    : _cubicBezierEasingFunction_3;
            }

            // - - - Layer aggregator
            // - Transforms: M
            // Path
            PathKeyFrameAnimation PathKeyFrameAnimation_0()
            {
                // Frame 0.
                var result = CreatePathKeyFrameAnimation(0F, Path_0(), StepThenHoldEasingFunction());
                // Frame 10.
                result.InsertKeyFrame(0.0909090936F, Path_0(), HoldThenStepEasingFunction());
                // Frame 35.
                result.InsertKeyFrame(0.318181813F, Path_1(), CubicBezierEasingFunction_0());
                // Frame 55.
                result.InsertKeyFrame(0.5F, Path_1(), CubicBezierEasingFunction_1());
                // Frame 80.
                result.InsertKeyFrame(0.727272749F, Path_0(), CubicBezierEasingFunction_2());
                return result;
            }

            // Layer aggregator
            ShapeVisual ShapeVisual_0()
            {
                var result = _c.CreateShapeVisual();
                result.Size = new Vector2(500F, 500F);
                var shapes = result.Shapes;
                shapes.Add(ContainerShape_0());
                shapes.Add(ContainerShape_1());
                return result;
            }

            StepEasingFunction HoldThenStepEasingFunction()
            {
                if (_holdThenStepEasingFunction != null) { return _holdThenStepEasingFunction; }
                var result = _holdThenStepEasingFunction = _c.CreateStepEasingFunction();
                result.IsFinalStepSingleFrame = true;
                return result;
            }

            StepEasingFunction StepThenHoldEasingFunction()
            {
                if (_stepThenHoldEasingFunction != null) { return _stepThenHoldEasingFunction; }
                var result = _stepThenHoldEasingFunction = _c.CreateStepEasingFunction();
                result.IsInitialStepSingleFrame = true;
                return result;
            }

            // - - Layer aggregator
            // Transforms: Shape Layer 12
            // Offset
            Vector2KeyFrameAnimation OffsetVector2Animation_0()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(80F, 65.6240005F), StepThenHoldEasingFunction());
                // Frame 17.
                result.InsertKeyFrame(0.154545456F, new Vector2(80F, 65.6240005F), HoldThenStepEasingFunction());
                // Frame 33.
                result.InsertKeyFrame(0.300000012F, new Vector2(110F, 55.6240005F), CubicBezierEasingFunction_0());
                // Frame 53.
                result.InsertKeyFrame(0.481818169F, new Vector2(110F, 55.6240005F), CubicBezierEasingFunction_3());
                // Frame 87.
                result.InsertKeyFrame(0.790909111F, new Vector2(80F, 65.6240005F), CubicBezierEasingFunction_2());
                return result;
            }

            // - - Layer aggregator
            // Transforms: Shape Layer 17
            // Offset
            Vector2KeyFrameAnimation OffsetVector2Animation_1()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(280.579987F, 65.6240005F), StepThenHoldEasingFunction());
                // Frame 17.
                result.InsertKeyFrame(0.154545456F, new Vector2(280.579987F, 65.6240005F), HoldThenStepEasingFunction());
                // Frame 33.
                result.InsertKeyFrame(0.300000012F, new Vector2(250.580002F, 55.6240005F), CubicBezierEasingFunction_0());
                // Frame 53.
                result.InsertKeyFrame(0.481818169F, new Vector2(250.580002F, 55.6240005F), CubicBezierEasingFunction_3());
                // Frame 87.
                result.InsertKeyFrame(0.790909111F, new Vector2(280.579987F, 65.6240005F), CubicBezierEasingFunction_2());
                return result;
            }

            // - Layer aggregator
            // Offset
            Vector2KeyFrameAnimation OffsetVector2Animation_2()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(200F, 174.376007F), HoldThenStepEasingFunction());
                // Frame 10.
                result.InsertKeyFrame(0.0909090936F, new Vector2(200F, 154.376007F), CubicBezierEasingFunction_0());
                // Frame 35.
                result.InsertKeyFrame(0.318181813F, new Vector2(200F, 234.376007F), CubicBezierEasingFunction_0());
                // Frame 55.
                result.InsertKeyFrame(0.5F, new Vector2(200F, 234.376007F), CubicBezierEasingFunction_3());
                // Frame 80.
                result.InsertKeyFrame(0.727272749F, new Vector2(200F, 154.376007F), CubicBezierEasingFunction_0());
                // Frame 90.
                result.InsertKeyFrame(0.818181813F, new Vector2(200F, 174.376007F), CubicBezierEasingFunction_0());
                return result;
            }

            // - Layer aggregator
            // Scale
            Vector2KeyFrameAnimation ScaleVector2Animation_0()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(1F, 1F), StepThenHoldEasingFunction());
                // Frame 8.
                result.InsertKeyFrame(0.0727272704F, new Vector2(1F, 1F), HoldThenStepEasingFunction());
                // Frame 16.
                result.InsertKeyFrame(0.145454541F, new Vector2(1.02999997F, 0.970000029F), CubicBezierEasingFunction_0());
                // Frame 83.
                result.InsertKeyFrame(0.75454545F, new Vector2(1.02999997F, 0.970000029F), CubicBezierEasingFunction_0());
                // Frame 92.
                result.InsertKeyFrame(0.836363614F, new Vector2(1F, 1F), CubicBezierEasingFunction_0());
                return result;
            }

            // Scale
            Vector2KeyFrameAnimation ScaleVector2Animation_1()
            {
                // Frame 0.
                if (_scaleVector2Animation_1 != null) { return _scaleVector2Animation_1; }
                var result = _scaleVector2Animation_1 = CreateVector2KeyFrameAnimation(0F, new Vector2(1.47253001F, 1.47253001F), HoldThenStepEasingFunction());
                // Frame 4.13.
                result.InsertKeyFrame(0.0375000015F, new Vector2(1.54999995F, 1.54999995F), CubicBezierEasingFunction_0());
                // Frame 8.25.
                result.InsertKeyFrame(0.075000003F, new Vector2(1.47253001F, 1.47253001F), CubicBezierEasingFunction_0());
                // Frame 12.37.
                result.InsertKeyFrame(0.112499997F, new Vector2(1.54999995F, 1.54999995F), CubicBezierEasingFunction_0());
                // Frame 16.5.
                result.InsertKeyFrame(0.150000006F, new Vector2(1.47253001F, 1.47253001F), CubicBezierEasingFunction_0());
                // Frame 20.63.
                result.InsertKeyFrame(0.1875F, new Vector2(1.54999995F, 1.54999995F), CubicBezierEasingFunction_0());
                // Frame 24.75.
                result.InsertKeyFrame(0.224999994F, new Vector2(1.47253001F, 1.47253001F), CubicBezierEasingFunction_0());
                // Frame 28.87.
                result.InsertKeyFrame(0.262499988F, new Vector2(1.54999995F, 1.54999995F), CubicBezierEasingFunction_0());
                // Frame 33.
                result.InsertKeyFrame(0.300000012F, new Vector2(1.47253001F, 1.47253001F), CubicBezierEasingFunction_0());
                // Frame 37.13.
                result.InsertKeyFrame(0.337500006F, new Vector2(1.54999995F, 1.54999995F), CubicBezierEasingFunction_0());
                // Frame 41.25.
                result.InsertKeyFrame(0.375F, new Vector2(1.47253001F, 1.47253001F), CubicBezierEasingFunction_0());
                // Frame 45.37.
                result.InsertKeyFrame(0.412499994F, new Vector2(1.54999995F, 1.54999995F), CubicBezierEasingFunction_0());
                // Frame 49.5.
                result.InsertKeyFrame(0.449999988F, new Vector2(1.47253001F, 1.47253001F), CubicBezierEasingFunction_0());
                // Frame 53.63.
                result.InsertKeyFrame(0.487500012F, new Vector2(1.54999995F, 1.54999995F), CubicBezierEasingFunction_0());
                // Frame 57.75.
                result.InsertKeyFrame(0.524999976F, new Vector2(1.47253001F, 1.47253001F), CubicBezierEasingFunction_0());
                // Frame 61.88.
                result.InsertKeyFrame(0.5625F, new Vector2(1.54999995F, 1.54999995F), CubicBezierEasingFunction_0());
                // Frame 66.
                result.InsertKeyFrame(0.600000024F, new Vector2(1.47253001F, 1.47253001F), CubicBezierEasingFunction_0());
                // Frame 70.12.
                result.InsertKeyFrame(0.637499988F, new Vector2(1.54999995F, 1.54999995F), CubicBezierEasingFunction_0());
                // Frame 74.25.
                result.InsertKeyFrame(0.675000012F, new Vector2(1.47253001F, 1.47253001F), CubicBezierEasingFunction_0());
                // Frame 78.37.
                result.InsertKeyFrame(0.712499976F, new Vector2(1.54999995F, 1.54999995F), CubicBezierEasingFunction_0());
                // Frame 82.5.
                result.InsertKeyFrame(0.75F, new Vector2(1.47253001F, 1.47253001F), CubicBezierEasingFunction_0());
                // Frame 86.63.
                result.InsertKeyFrame(0.787500024F, new Vector2(1.54999995F, 1.54999995F), CubicBezierEasingFunction_0());
                // Frame 90.75.
                result.InsertKeyFrame(0.824999988F, new Vector2(1.47253001F, 1.47253001F), CubicBezierEasingFunction_0());
                // Frame 94.88.
                result.InsertKeyFrame(0.862500012F, new Vector2(1.54999995F, 1.54999995F), CubicBezierEasingFunction_0());
                // Frame 99.
                result.InsertKeyFrame(0.899999976F, new Vector2(1.47253001F, 1.47253001F), CubicBezierEasingFunction_0());
                return result;
            }

            // Scale
            Vector2KeyFrameAnimation ScaleVector2Animation_2()
            {
                // Frame 0.
                if (_scaleVector2Animation_2 != null) { return _scaleVector2Animation_2; }
                var result = _scaleVector2Animation_2 = CreateVector2KeyFrameAnimation(0F, new Vector2(1.09889996F, 1.09889996F), HoldThenStepEasingFunction());
                // Frame 4.13.
                result.InsertKeyFrame(0.0375000015F, new Vector2(0.899999976F, 0.899999976F), CubicBezierEasingFunction_0());
                // Frame 8.25.
                result.InsertKeyFrame(0.075000003F, new Vector2(1.09889996F, 1.09889996F), CubicBezierEasingFunction_0());
                // Frame 12.37.
                result.InsertKeyFrame(0.112499997F, new Vector2(0.899999976F, 0.899999976F), CubicBezierEasingFunction_0());
                // Frame 16.5.
                result.InsertKeyFrame(0.150000006F, new Vector2(1.09889996F, 1.09889996F), CubicBezierEasingFunction_0());
                // Frame 20.63.
                result.InsertKeyFrame(0.1875F, new Vector2(0.899999976F, 0.899999976F), CubicBezierEasingFunction_0());
                // Frame 24.75.
                result.InsertKeyFrame(0.224999994F, new Vector2(1.09889996F, 1.09889996F), CubicBezierEasingFunction_0());
                // Frame 28.87.
                result.InsertKeyFrame(0.262499988F, new Vector2(0.899999976F, 0.899999976F), CubicBezierEasingFunction_0());
                // Frame 33.
                result.InsertKeyFrame(0.300000012F, new Vector2(1.09889996F, 1.09889996F), CubicBezierEasingFunction_0());
                // Frame 37.13.
                result.InsertKeyFrame(0.337500006F, new Vector2(0.899999976F, 0.899999976F), CubicBezierEasingFunction_0());
                // Frame 41.25.
                result.InsertKeyFrame(0.375F, new Vector2(1.09889996F, 1.09889996F), CubicBezierEasingFunction_0());
                // Frame 45.37.
                result.InsertKeyFrame(0.412499994F, new Vector2(0.899999976F, 0.899999976F), CubicBezierEasingFunction_0());
                // Frame 49.5.
                result.InsertKeyFrame(0.449999988F, new Vector2(1.09889996F, 1.09889996F), CubicBezierEasingFunction_0());
                // Frame 53.63.
                result.InsertKeyFrame(0.487500012F, new Vector2(0.899999976F, 0.899999976F), CubicBezierEasingFunction_0());
                // Frame 57.75.
                result.InsertKeyFrame(0.524999976F, new Vector2(1.09889996F, 1.09889996F), CubicBezierEasingFunction_0());
                // Frame 61.88.
                result.InsertKeyFrame(0.5625F, new Vector2(0.899999976F, 0.899999976F), CubicBezierEasingFunction_0());
                // Frame 66.
                result.InsertKeyFrame(0.600000024F, new Vector2(1.09889996F, 1.09889996F), CubicBezierEasingFunction_0());
                // Frame 70.12.
                result.InsertKeyFrame(0.637499988F, new Vector2(0.899999976F, 0.899999976F), CubicBezierEasingFunction_0());
                // Frame 74.25.
                result.InsertKeyFrame(0.675000012F, new Vector2(1.09889996F, 1.09889996F), CubicBezierEasingFunction_0());
                // Frame 78.37.
                result.InsertKeyFrame(0.712499976F, new Vector2(0.899999976F, 0.899999976F), CubicBezierEasingFunction_0());
                // Frame 82.5.
                result.InsertKeyFrame(0.75F, new Vector2(1.09889996F, 1.09889996F), CubicBezierEasingFunction_0());
                // Frame 86.63.
                result.InsertKeyFrame(0.787500024F, new Vector2(0.899999976F, 0.899999976F), CubicBezierEasingFunction_0());
                // Frame 90.75.
                result.InsertKeyFrame(0.824999988F, new Vector2(1.09889996F, 1.09889996F), CubicBezierEasingFunction_0());
                // Frame 94.88.
                result.InsertKeyFrame(0.862500012F, new Vector2(0.899999976F, 0.899999976F), CubicBezierEasingFunction_0());
                // Frame 99.
                result.InsertKeyFrame(0.899999976F, new Vector2(1.09889996F, 1.09889996F), CubicBezierEasingFunction_0());
                return result;
            }

            // - - Layer aggregator
            // Transforms: Shape Layer 2
            // Scale
            Vector2KeyFrameAnimation ScaleVector2Animation_3()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(1F, 1F), StepThenHoldEasingFunction());
                // Frame 10.
                result.InsertKeyFrame(0.0909090936F, new Vector2(1F, 1F), HoldThenStepEasingFunction());
                // Frame 35.
                result.InsertKeyFrame(0.318181813F, new Vector2(1.07000005F, 1.07000005F), CubicBezierEasingFunction_0());
                // Frame 55.
                result.InsertKeyFrame(0.5F, new Vector2(1.07000005F, 1.07000005F), CubicBezierEasingFunction_1());
                // Frame 80.
                result.InsertKeyFrame(0.727272749F, new Vector2(1F, 1F), CubicBezierEasingFunction_2());
                return result;
            }

            // - - Layer aggregator
            // Transforms: Shape Layer 12
            // Scale
            Vector2KeyFrameAnimation ScaleVector2Animation_4()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(0.800000012F, 0.800000012F), StepThenHoldEasingFunction());
                // Frame 17.
                result.InsertKeyFrame(0.154545456F, new Vector2(0.800000012F, 0.800000012F), HoldThenStepEasingFunction());
                // Frame 33.
                result.InsertKeyFrame(0.300000012F, new Vector2(0.800000012F, 0.800000012F), CubicBezierEasingFunction_0());
                // Frame 53.
                result.InsertKeyFrame(0.481818169F, new Vector2(0.800000012F, 0.800000012F), CubicBezierEasingFunction_1());
                // Frame 87.
                result.InsertKeyFrame(0.790909111F, new Vector2(0.800000012F, 0.800000012F), CubicBezierEasingFunction_2());
                return result;
            }

            // - - Layer aggregator
            // Transforms: Shape Layer 13
            // Scale
            Vector2KeyFrameAnimation ScaleVector2Animation_5()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(-1F, 1F), StepThenHoldEasingFunction());
                // Frame 10.
                result.InsertKeyFrame(0.0909090936F, new Vector2(-1F, 1F), HoldThenStepEasingFunction());
                // Frame 35.
                result.InsertKeyFrame(0.318181813F, new Vector2(-1.07000005F, 1.07000005F), CubicBezierEasingFunction_0());
                // Frame 55.
                result.InsertKeyFrame(0.5F, new Vector2(-1.07000005F, 1.07000005F), CubicBezierEasingFunction_1());
                // Frame 80.
                result.InsertKeyFrame(0.727272749F, new Vector2(-1F, 1F), CubicBezierEasingFunction_2());
                return result;
            }

            // - - Layer aggregator
            // Transforms: Shape Layer 17
            // Scale
            Vector2KeyFrameAnimation ScaleVector2Animation_6()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(-0.800000012F, 0.800000012F), StepThenHoldEasingFunction());
                // Frame 17.
                result.InsertKeyFrame(0.154545456F, new Vector2(-0.800000012F, 0.800000012F), HoldThenStepEasingFunction());
                // Frame 33.
                result.InsertKeyFrame(0.300000012F, new Vector2(-0.800000012F, 0.800000012F), CubicBezierEasingFunction_0());
                // Frame 53.
                result.InsertKeyFrame(0.481818169F, new Vector2(-0.800000012F, 0.800000012F), CubicBezierEasingFunction_1());
                // Frame 87.
                result.InsertKeyFrame(0.790909111F, new Vector2(-0.800000012F, 0.800000012F), CubicBezierEasingFunction_2());
                return result;
            }

            // - - Layer aggregator
            // Transforms: M
            // Scale
            Vector2KeyFrameAnimation ScaleVector2Animation_7()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(0.899999976F, 0.899999976F), StepThenHoldEasingFunction());
                // Frame 10.
                result.InsertKeyFrame(0.0909090936F, new Vector2(0.899999976F, 0.899999976F), HoldThenStepEasingFunction());
                // Frame 35.
                result.InsertKeyFrame(0.318181813F, new Vector2(0.699999988F, 0.699999988F), CubicBezierEasingFunction_0());
                // Frame 55.
                result.InsertKeyFrame(0.5F, new Vector2(0.699999988F, 0.699999988F), CubicBezierEasingFunction_1());
                // Frame 80.
                result.InsertKeyFrame(0.727272749F, new Vector2(0.899999976F, 0.899999976F), CubicBezierEasingFunction_2());
                return result;
            }

            internal Sad__Failed_AnimatedVisual(
                Compositor compositor
                )
            {
                _c = compositor;
                _reusableExpressionAnimation = compositor.CreateExpressionAnimation();
                Root();
            }

            public Visual RootVisual => _root;
            public TimeSpan Duration => TimeSpan.FromTicks(c_durationTicks);
            public Vector2 Size => new Vector2(500F, 500F);
            void IDisposable.Dispose() => _root?.Dispose();

            public void CreateAnimations()
            {
                _containerShape_0.StartAnimation("Scale", ScaleVector2Animation_0(), AnimationController_0());
                _containerShape_1.StartAnimation("Offset", OffsetVector2Animation_2(), AnimationController_0());
                _containerShape_2.StartAnimation("Scale", ScaleVector2Animation_3(), AnimationController_0());
                _containerShape_3.StartAnimation("Scale", ScaleVector2Animation_1(), AnimationController_0());
                _containerShape_4.StartAnimation("Scale", ScaleVector2Animation_2(), AnimationController_0());
                _containerShape_5.StartAnimation("Scale", ScaleVector2Animation_5(), AnimationController_0());
                _containerShape_6.StartAnimation("Scale", ScaleVector2Animation_1(), AnimationController_0());
                _containerShape_7.StartAnimation("Scale", ScaleVector2Animation_2(), AnimationController_0());
                _pathGeometry_1.StartAnimation("Path", PathKeyFrameAnimation_0(), AnimationController_0());
                _spriteShape_05.StartAnimation("Scale", ScaleVector2Animation_4(), AnimationController_0());
                _spriteShape_05.StartAnimation("Offset", OffsetVector2Animation_0(), AnimationController_0());
                _spriteShape_10.StartAnimation("Scale", ScaleVector2Animation_6(), AnimationController_0());
                _spriteShape_10.StartAnimation("Offset", OffsetVector2Animation_1(), AnimationController_0());
                _spriteShape_11.StartAnimation("Scale", ScaleVector2Animation_7(), AnimationController_0());
            }

            public void DestroyAnimations()
            {
                _containerShape_0.StopAnimation("Scale");
                _containerShape_1.StopAnimation("Offset");
                _containerShape_2.StopAnimation("Scale");
                _containerShape_3.StopAnimation("Scale");
                _containerShape_4.StopAnimation("Scale");
                _containerShape_5.StopAnimation("Scale");
                _containerShape_6.StopAnimation("Scale");
                _containerShape_7.StopAnimation("Scale");
                _pathGeometry_1.StopAnimation("Path");
                _spriteShape_05.StopAnimation("Scale");
                _spriteShape_05.StopAnimation("Offset");
                _spriteShape_10.StopAnimation("Scale");
                _spriteShape_10.StopAnimation("Offset");
                _spriteShape_11.StopAnimation("Scale");
            }

        }
    }
}
